<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="stylesP.css">
    <title>Protoss Zealot</title>

</head>

<body>
    <nav id="nav">
        <image id="protoss-emblem" src="protoss-photos/Protoss_emblem.jpg" alt="protoss"></image>
        <h1>Zealot</h1>
        <div class="spacer">&nbsp;</div>
        <ul>
            <li><a href="terran.html">Terran</li>
            <li><a href="index.html">Protoss</a></li>
            <li><a href="zerg.html">Zerg</a></li>
        </ul>
    </nav>
    <div id="image">
        <image id="protoss_zealot" src="protoss-photos/protoss_zealot.jpg" alt="zealot">
    </div>
    <div id="main-text">
        <h2>Zealot</h2>
        <ul>
            <li>Warrior Class</li>
            <li>Utilizes plasma blades on each arm to slash through enemies with ease</li>
            <li>Front line unit</li>
            <li>Utilizes shields to protect itself from enemy attacks</li>
            <li>Psionic abilities focused on battle</li>
        </ul>
    </div>
    <div style="border: 1px solid rgb(16, 16, 209)" class="quotes">
        <h3>Selected Unit Quotes:</h3>
        <ul>
            <li>
                <blockquote cite="https://starcraft.fandom.com/wiki/StarCraft_unit_quotations">Executor?</blockquote>
            </li>
            <li>
                <blockquote cite="https://starcraft.fandom.com/wiki/StarCraft_unit_quotations">Your command?
                </blockquote>
            </li>
            <li>
                <blockquote cite="https://starcraft.fandom.com/wiki/StarCraft_unit_quotations">What would you ask of me?
                </blockquote>
            </li>
            <li>
                <blockquote cite="https://starcraft.fandom.com/wiki/StarCraft_unit_quotations">I hunger for battle...
                </blockquote>
            </li>
        </ul>
        <div class="quotes">
            <h3>Confirming Orders Quotes:</h3>
            <ul>
                <li>
                    <blockquote cite="https://starcraft.fandom.com/wiki/StarCraft_unit_quotations">For Aiur!
                    </blockquote>
                </li>
                <li>
                    <blockquote cite="https://starcraft.fandom.com/wiki/StarCraft_unit_quotations">Immediately!
                    </blockquote>
                </li>
                <li>
                    <blockquote cite="https://starcraft.fandom.com/wiki/StarCraft_unit_quotations">Nach ta' kala
                    </blockquote>
                </li>
                <li>
                    <blockquote cite="https://starcraft.fandom.com/wiki/StarCraft_unit_quotations">As you will!
                    </blockquote>
                </li>
            </ul>
        </div>
    </div>


    <div id="upgrades">
        <ul>
            <li id="protoss-weapons-upgrade">Increases damage of ground units by 1. Max 3+ weapons upgrade</li>
            <li id="protoss-armor-upgrade">Increases armor of ground units by 1. Max 3+ armor upgrade</li>
            <li id="protoss-shields-upgrade">Increases shields of all units by 1. Max 3+ shields upgrade</li>
            <li id="charge-upgrade">Enables zealots to charge at enemies by doubling their movement speed temporarily
            </li>
        </ul>
    </div>

    <div id="video">
        <iframe
            src="https://www.youtube.com/embed/M_XwzBMTJaM?si=Vaxx422dKTy4-Rd-&amp;clip=UgkxtVGTfsljp8gU154VXGFGIAEMWWEUXgUs&amp;clipt=EKW8AhjglgU"
            title="YouTube video player" frameborder="0"
            allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"
            allowfullscreen></iframe>
    </div>

    <div id="strong">
        <h2><u>Strong Against</u></h2>
        <ul>
            <li class="race">Zerg:
                <ul>
                    <li>Zergling</li>
                    <li>Hydralisk</li>
                </ul>
            </li>
            <li class="race">Protoss:
                <ul>
                    <li>Immortals</li>
                </ul>
            </li>
        </ul>
    </div>
    <div id="weak">
        <h2><u>Weak Against</u></h2>
        <ul>
            <li class="race">Terran:
            <li>Hellion</li>
            <li>Hellbat</li>
            </li>
            <li class="race">Zerg:
            <li>Roaches</li>
            <li>Banelings</li>
            </li>
            <li class="race">
            <li>Collosi</li>
            </li>
        </ul>
    </div>

    <div id="lore">
        <blockquote cite="https://starcraft.fandom.com/wiki/Zealot">
            <p>
                Zealots are lower-ranked Templar who have yet to reach the upper levels of the Khala. They form the
                backbone of the protoss military, and have been utilized since before the Discord. At least some,
                if not all Khalai zealots are members of the Zealot Order. Zealots honor the moon Saalok as their
                order's symbol, which they call the Zealous Round. Zealots can operate in platoons and legions.
                During the Great War, many zealots demonstrated their fearlessness by going without head armor, a
                practice that has since been discontinued.

                The Tal'darim also employ zealots. As the lowest ranking links in the Chain of Ascension, they are
                the ones most eager to prove themselves.

                Ihan-rii zealots are fanatic believers in the xel'naga, believing that one day they would ascend to
                eternal godhood.

                After the End War, many zealots took part in the artistic celebration of the Golden Age of Expansion,
                changing their armor to the more ornate style of the era.
            </p>
        </blockquote>
    </div>

</body>

</html>
